version: '3'
services:
  myapp:
    image: 391363380726.dkr.ecr.us-west-2.amazonaws.com/my-app:1.0
    ports:
      - 3003:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongoui:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
